<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Enrollment;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class PaystackWebhookController extends Controller
{
    public function handleWebhook(Request $request)
    {
        $paystackSignature = $request->header('x-paystack-signature');
        $secretKey = config('services.paystack.secret_key');

        if (!$paystackSignature || $paystackSignature !== hash_hmac('sha512', $request->getContent(), $secretKey)) {
            Log::error('Unauthorized Webhook Attempt: Invalid Signature');
            return response()->json(['message' => 'Unauthorized'], 401);
        }

        $payload = $request->all();

        if (($payload['event'] ?? '') === 'charge.success') {
            $data = $payload['data'];
            $reference = $data['reference'];

            // Resource-store purchases (RES_*) are handled separately — the
            // enrollment/installment path below is untouched.
            if (str_starts_with($reference, 'RES_')) {
                $this->handleResourcePurchase($reference, $secretKey, $data);
                return response()->json(['status' => 'success']);
            }

            $enrollment = Enrollment::where('payment_reference', $reference)->first();

            if ($enrollment) {
                // ---- FIRST PAYMENT (full, early-bird, or 1st installment) ----
                if ($enrollment->status !== 'paid') {
                    $verify = Http::withToken($secretKey)
                        ->get("https://api.paystack.co/transaction/verify/{$reference}");

                    if ($verify->successful() && $verify->json('data.status') === 'success') {

                        $paystackAmount = $verify->json('data.amount') / 100;

                        if ((float)$paystackAmount === (float)$enrollment->amount) {

                            // 1. Finalize Enrollment Status
                            $enrollment->update([
                                'status' => 'paid',
                                'paid_at' => now(),
                                'paystack_payload' => $data
                            ]);

                            // 1b. Installment: schedule the 2nd payment due date. The
                            //     installments:process command fires the n8n payment-link
                            //     webhook on the due date and suspends access if it goes unpaid.
                            if ($enrollment->plan_type === 'installment' && (float)$enrollment->balance_due > 0) {
                                $enrollment->update([
                                    'second_payment_due_at' => now()->addDays((int) config('accelerator.installment_due_days', 14)),
                                ]);
                            }

                            // 2. Provision User for Fortify Access
                            // We generate a high-entropy temporary password
                            $tempPassword = Str::random(14);

                            User::firstOrCreate(
                                ['email' => $enrollment->email],
                                [
                                    'name' => $enrollment->full_name,
                                    'password' => Hash::make($tempPassword),
                                ]
                            );

                            // 3. Dispatch Fulfillment via n8n
                            $this->triggerAutomation($enrollment, $tempPassword);

                        } else {
                            Log::error("Security Alert: Amount Mismatch for {$reference}");
                            $enrollment->update(['status' => 'amount_mismatch']);
                        }
                    }
                }
            } else {
                // ---- SECOND INSTALLMENT PAYMENT (paid via the n8n link, different reference) ----
                $this->handleSecondInstallment($reference, $secretKey, $data);
            }
        }

        return response()->json(['status' => 'success']);
    }

    /**
     * Reconcile a second installment payment. The reference was pre-generated by
     * the installments:process command and stored on the enrollment, so a
     * charge.success on it maps cleanly back to the right buyer.
     */
    private function handleSecondInstallment(string $reference, string $secretKey, array $data): void
    {
        $enrollment = Enrollment::where('second_payment_reference', $reference)
            ->where('second_payment_status', '!=', 'paid')
            ->first();

        if (! $enrollment) {
            return; // not an installment 2nd payment we know about
        }

        $verify = Http::withToken($secretKey)
            ->get("https://api.paystack.co/transaction/verify/{$reference}");

        if (! $verify->successful() || $verify->json('data.status') !== 'success') {
            return;
        }

        $paidAmount = $verify->json('data.amount') / 100;

        if ((float)$paidAmount === (float)$enrollment->balance_due) {
            $enrollment->update([
                'second_payment_status' => 'paid',
                'balance_due' => 0,
                'access_suspended' => false, // reinstate access if it had been suspended
            ]);

            $this->triggerInstallmentCompleted($enrollment, $data);
        } else {
            Log::error("Installment Amount Mismatch for {$reference}: paid {$paidAmount}, expected {$enrollment->balance_due}");
        }
    }

    /**
     * A paid-resource purchase (RES_*): verify server-side, mark paid, deliver.
     * The access page reveals the link once status=paid; the n8n email is a bonus.
     */
    private function handleResourcePurchase(string $reference, string $secretKey, array $data): void
    {
        $purchase = \App\Models\ResourcePurchase::where('payment_reference', $reference)
            ->where('status', '!=', 'paid')
            ->first();

        if (! $purchase) {
            return;
        }

        $verify = Http::withToken($secretKey)->get("https://api.paystack.co/transaction/verify/{$reference}");

        if (! $verify->successful() || $verify->json('data.status') !== 'success') {
            return;
        }

        $paidAmount = $verify->json('data.amount') / 100;

        if ((float) $paidAmount !== (float) $purchase->amount) {
            Log::error("Resource purchase amount mismatch for {$reference}: paid {$paidAmount}, expected {$purchase->amount}");
            $purchase->update(['status' => 'amount_mismatch']);
            return;
        }

        $purchase->update(['status' => 'paid', 'paid_at' => now()]);
        \App\Support\ResourceDelivery::deliver($purchase->fresh());
    }

    private function triggerInstallmentCompleted($enrollment, $data): void
    {
        $url = config('services.n8n.installment_webhook') ?: config('services.n8n.enrollment_webhook');

        if (! $url) {
            return;
        }

        try {
            Http::post($url, [
                'event' => 'installment_completed',
                'gateway' => 'paystack',
                'full_name' => $enrollment->full_name,
                'email' => $enrollment->email,
                'phone' => $enrollment->whatsapp,
                'amount' => $enrollment->amount_total,
                'currency' => $enrollment->currency,
                'reference' => $enrollment->second_payment_reference,
                'original_reference' => $enrollment->payment_reference,
            ]);
        } catch (\Exception $e) {
            Log::error("Installment completion trigger failed for {$enrollment->email}: " . $e->getMessage());
        }
    }

    private function triggerAutomation($enrollment, $temporaryPassword)
    {
        try {
            Http::post(config('services.n8n.enrollment_webhook'), [
                'event' => 'enrollment_finalized',
                'gateway' => 'paystack',
                'full_name' => $enrollment->full_name,
                'email' => $enrollment->email,
                'phone' => $enrollment->whatsapp,
                'temp_password' => $temporaryPassword,
                'login_url' => url('/login'),
                'amount' => $enrollment->amount,
                'currency' => $enrollment->currency,
                'plan_type' => $enrollment->plan_type,
                'amount_total' => $enrollment->amount_total,
                'balance_due' => $enrollment->balance_due,
                'second_payment_status' => $enrollment->second_payment_status,
                'reference' => $enrollment->payment_reference,
                'paid_at' => $enrollment->paid_at->toIso8601String(),
            ]);
        } catch (\Exception $e) {
            Log::error("Critical: n8n Provisioning Trigger Failed for {$enrollment->email}: " . $e->getMessage());
        }
    }
}